### ISSUE TITLE
Story: Hyperlink Scanner

### ISSUE THREAD

**Issue by jonthemango** [YannCedric/Simple-Camera#4]
https://github.com/ramzouza/Simple-Camera/wiki/Hyperlink-Scanner

- [x] Unit Tests
- [x] UI Tests
- [x] Link scannable

**Comment by ramzouza** [comment]
We currently have a bug, if you scan a picture that does not contain any text the application will crash.  If the lens finds text but no hyperlink an appropriate error message will appear.   However if the picture scanned contains no text instead of returning the appropriate error the lens causes the application to crash 

- [x] Fixed

**Comment by jonthemango** [comment]
Only bug is that it requires you to take photo and then activate the detection. Aside from that it's finished.
